### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by kevinorin** [MarkXA/ddrmenutemplates#1]
This isn't really a issue but which template/folder would I use for a "Accordion" menu or is that not included? Looking all over for how to setup a accordion DDRMenu in DNN Evoq.

Thanks,
Kevin W.

**Comment by kevinorin** [comment]
Anyone know where I can find the Accordion assets?

**Comment by kevinorin** [comment]
Does anyone know where I can find the DDR Menu Accordion Template assets?

**Comment by MarkXA** [comment]
There was an accordion template once, but the plugin it was based on got deprecated and stopped working with current versions of jQuery. If anyone wants to submit a more modern one then that would be great :)

**Comment by kevinorin** [comment]
I actually found the Accordion Template and it works fine on DNN Evoq. How can I add into the repo?
